export interface City {
  name_ar: string;
  name_en: string;
}

export interface Governorate {
  id: string; // English name or a unique identifier
  name_ar: string;
  name_en: string;
  cities: City[];
}

export const egyptianGovernorates: Governorate[] = [
  {
    id: "cairo",
    name_ar: "القاهرة",
    name_en: "Cairo",
    cities: [
      { name_ar: "عابدين", name_en: "Abdeen" },
      { name_ar: "عين شمس", name_en: "Ain Shams" },
      { name_ar: "الأميرية", name_en: "Amreya" },
      { name_ar: "الأزبكية", name_en: "Azbakeya" },
      { name_ar: "البساتين", name_en: "Basateen" },
      { name_ar: "باب الشعرية", name_en: "Bab El Sharia" },
      { name_ar: "مصر القديمة", name_en: "Old Cairo (Masr Al-Qadima)" },
      { name_ar: "الخليفة", name_en: "El Khalifa" },
      { name_ar: "الدرب الأحمر", name_en: "Darb El Ahmar" },
      { name_ar: "الجمالية", name_en: "Gamaleya" },
      { name_ar: "مصر الجديدة", name_en: "Heliopolis" },
      { name_ar: "حلوان", name_en: "Helwan" },
      { name_ar: "المعادي", name_en: "Maadi" },
      { name_ar: "المرج", name_en: "Marg" },
      { name_ar: "المطرية", name_en: "Matareya" },
      { name_ar: "الموسكي", name_en: "Mosky" },
      { name_ar: "القاهرة الجديدة", name_en: "New Cairo" },
      { name_ar: "النزهة", name_en: "Nozha" },
      { name_ar: "قصر النيل", name_en: "Kasr El Nil" },
      { name_ar: "روض الفرج", name_en: "Rod El Farag" },
      { name_ar: "السيدة زينب", name_en: "Sayeda Zeinab" },
      { name_ar: "شبرا", name_en: "Shubra" },
      { name_ar: "السلام أول", name_en: "Salam Awal" },
      { name_ar: "السلام ثان", name_en: "Salam Thani" },
      { name_ar: "الساحل", name_en: "Sahel" },
      { name_ar: "الشرابية", name_en: "Sharabiya" },
      { name_ar: "الشروق", name_en: "El Shorouk" },
      { name_ar: "التبين", name_en: "El Tebbin" },
      { name_ar: "الوايلي", name_en: "Wayli" },
      { name_ar: "الزاوية الحمراء", name_en: "Zawya El Hamra" },
      { name_ar: "الزيتون", name_en: "Zeitoun" },
      { name_ar: "مدينة بدر", name_en: "Badr City" },
      { name_ar: "وسط القاهرة", name_en: "Downtown Cairo" },
      { name_ar: "غرب القاهرة", name_en: "West Cairo" },
      { name_ar: "منشأة ناصر", name_en: "Manshiyat Naser" },
      { name_ar: "15 مايو", name_en: "15th of May City" },
    ],
  },
  {
    id: "giza",
    name_ar: "الجيزة",
    name_en: "Giza",
    cities: [
      { name_ar: "الجيزة", name_en: "Giza" },
      { name_ar: "السادس من أكتوبر", name_en: "6th of October City" },
      { name_ar: "الشيخ زايد", name_en: "Sheikh Zayed City" },
      { name_ar: "الحوامدية", name_en: "Hawamdeyya" },
      { name_ar: "البدرشين", name_en: "Al Badrashein" },
      { name_ar: "الصف", name_en: "Saf" },
      { name_ar: "أطفيح", name_en: "Atfih" },
      { name_ar: "العياط", name_en: "Al Ayat" },
      { name_ar: "أبو النمرس", name_en: "Abu El Nomros" },
      { name_ar: "أوسيم", name_en: "Awsīm" },
      { name_ar: "كرداسة", name_en: "Kirdasah" },
      { name_ar: "منشأة القناطر", name_en: "Manshiyat Al Qanatir" },
      { name_ar: "الواحات البحرية", name_en: "Bahariya Oasis" },
      { name_ar: "الدقي", name_en: "Dokki" },
      { name_ar: "العجوزة", name_en: "Agouza" },
      { name_ar: "الهرم", name_en: "Haram" },
      { name_ar: "بولاق الدكرور", name_en: "Bulaq El Dakrour" },
      { name_ar: "إمبابة", name_en: "Imbaba" },
      { name_ar: "الوراق", name_en: "Warraq" },
    ],
  },
  {
    id: "alexandria",
    name_ar: "الإسكندرية",
    name_en: "Alexandria",
    cities: [
      { name_ar: "أبو قير", name_en: "Abu Qir" },
      { name_ar: "العجمي", name_en: "Agami" },
      { name_ar: "العامرية", name_en: "Amreya" },
      { name_ar: "الأنفوشي", name_en: "Anfoushi" },
      { name_ar: "العطارين", name_en: "Attarin" },
      { name_ar: "باب شرق", name_en: "Bab Sharq" },
      { name_ar: "برج العرب", name_en: "Borg El Arab" },
      { name_ar: "الدخيلة", name_en: "Dekhela" },
      { name_ar: "الجمرك", name_en: "Gomrok" },
      { name_ar: "كرموز", name_en: "Karmooz" },
      { name_ar: "اللبان", name_en: "Labban" },
      { name_ar: "المعمورة", name_en: "Maamoura" },
      { name_ar: "المنشية", name_en: "Mansheya" },
      { name_ar: "محرم بك", name_en: "Moharram Bey" },
      { name_ar: "المنتزه", name_en: "Montaza" },
      { name_ar: "الرمل", name_en: "Raml" },
      { name_ar: "سيدي بشر", name_en: "Sidi Bishr" },
      { name_ar: "سيدي جابر", name_en: "Sidi Gaber" },
      { name_ar: "سموحة", name_en: "Smouha" },
      { name_ar: "فيكتوريا", name_en: "Victoria" },
    ],
  },
  {
    id: "qalyubia",
    name_ar: "القليوبية",
    name_en: "Qalyubia",
    cities: [
      { name_ar: "بنها", name_en: "Banha" },
      { name_ar: "قليوب", name_en: "Qalyub" },
      { name_ar: "شبرا الخيمة", name_en: "Shubra El Kheima" },
      { name_ar: "القناطر الخيرية", name_en: "El Qanater El Khayreya" },
      { name_ar: "الخانكة", name_en: "El Khankah" },
      { name_ar: "كفر شكر", name_en: "Kafr Shukr" },
      { name_ar: "طوخ", name_en: "Toukh" },
      { name_ar: "قها", name_en: "Qaha" },
      { name_ar: "العبور", name_en: "Obour" },
      { name_ar: "الخصوص", name_en: "Khosous" },
      { name_ar: "شبين القناطر", name_en: "Shibin El Qanater" },
    ],
  },
  {
    id: "sharqia",
    name_ar: "الشرقية",
    name_en: "Sharqia",
    cities: [
      { name_ar: "الزقازيق", name_en: "Zagazig" },
      { name_ar: "العاشر من رمضان", name_en: "10th of Ramadan City" },
      { name_ar: "بلبيس", name_en: "Bilbeis" },
      { name_ar: "منيا القمح", name_en: "Minya El Qamh" },
      { name_ar: "أبو كبير", name_en: "Abu Kebir" },
      { name_ar: "فاقوس", name_en: "Faqous" },
      { name_ar: "ههيا", name_en: "Hehia" },
      { name_ar: "الإبراهيمية", name_en: "Ibrahimiya" },
      { name_ar: "ديرب نجم", name_en: "Deyerb Negm" },
      { name_ar: "كفر صقر", name_en: "Kafr Saqr" },
      { name_ar: "أولاد صقر", name_en: "Awlad Saqr" },
      { name_ar: "أبو حماد", name_en: "Abu Hammad" },
      { name_ar: "القرين", name_en: "El Qurain" },
      { name_ar: "الصالحية الجديدة", name_en: "New Salhia" },
      { name_ar: "مشتول السوق", name_en: "Mashtoul El Souk" },
    ],
  },
  {
    id: "dakahlia",
    name_ar: "الدقهلية",
    name_en: "Dakahlia",
    cities: [
      { name_ar: "المنصورة", name_en: "Mansoura" },
      { name_ar: "طلخا", name_en: "Talkha" },
      { name_ar: "ميت غمر", name_en: "Mit Ghamr" },
      { name_ar: "السنبلاوين", name_en: "El Senbellawein" },
      { name_ar: "دكرنس", name_en: "Dekernes" },
      { name_ar: "أجا", name_en: "Aga" },
      { name_ar: "منية النصر", name_en: "Menoufeya El Nasr" },
      { name_ar: "شربين", name_en: "Sherbin" },
      { name_ar: "بلقاس", name_en: "Belqas" },
      { name_ar: "المطرية", name_en: "Matareya (Dakahlia)" }, // To distinguish from Cairo's Matareya
      { name_ar: "المنزلة", name_en: "Manzala" },
      { name_ar: "جمصة", name_en: "Gamasa" },
      { name_ar: "نبروه", name_en: "Nabaroh" },
    ],
  },
  {
    id: "beheira",
    name_ar: "البحيرة",
    name_en: "Beheira",
    cities: [
      { name_ar: "دمنهور", name_en: "Damanhur" },
      { name_ar: "كفر الدوار", name_en: "Kafr El Dawwar" },
      { name_ar: "رشيد", name_en: "Rosetta (Rashid)" },
      { name_ar: "إدكو", name_en: "Edko" },
      { name_ar: "أبو المطامير", name_en: "Abu El Matamir" },
      { name_ar: "أبو حمص", name_en: "Abu Hummus" },
      { name_ar: "الدلنجات", name_en: "Delengat" },
      { name_ar: "المحمودية", name_en: "Mahmoudiyah" },
      { name_ar: "إيتاي البارود", name_en: "Itay El Barud" },
      { name_ar: "حوش عيسى", name_en: "Hosh Essa" },
      { name_ar: "شبراخيت", name_en: "Shubrakhit" },
      { name_ar: "كوم حمادة", name_en: "Kom Hamada" },
      { name_ar: "بدر", name_en: "Badr" },
      { name_ar: "وادي النطرون", name_en: "Wadi El Natrun" },
      { name_ar: "النوبارية الجديدة", name_en: "New Nubariya" },
    ],
  },
  {
    id: "gharbia",
    name_ar: "الغربية",
    name_en: "Gharbia",
    cities: [
      { name_ar: "طنطا", name_en: "Tanta" },
      { name_ar: "المحلة الكبرى", name_en: "El Mahalla El Kubra" },
      { name_ar: "كفر الزيات", name_en: "Kafr El Zayat" },
      { name_ar: "بسيون", name_en: "Basyoun" },
      { name_ar: "زفتى", name_en: "Zifta" },
      { name_ar: "السنطة", name_en: "El Santa" },
      { name_ar: "قطور", name_en: "Qutur" },
      { name_ar: "سمنود", name_en: "Samannoud" },
    ],
  },
  {
    id: "monufia",
    name_ar: "المنوفية",
    name_en: "Monufia",
    cities: [
      { name_ar: "شبين الكوم", name_en: "Shibin El Kom" },
      { name_ar: "منوف", name_en: "Menouf" },
      { name_ar: "مدينة السادات", name_en: "Sadat City" },
      { name_ar: "سرس الليان", name_en: "Sirs El Layan" },
      { name_ar: "أشمون", name_en: "Ashmoun" },
      { name_ar: "الباجور", name_en: "El Bagour" },
      { name_ar: "قويسنا", name_en: "Quweisna" },
      { name_ar: "بركة السبع", name_en: "Birket El Sab" },
      { name_ar: "تلا", name_en: "Tala" },
      { name_ar: "الشهداء", name_en: "El Shohada" },
    ],
  },
  {
    id: "kafr_el_sheikh",
    name_ar: "كفر الشيخ",
    name_en: "Kafr El Sheikh",
    cities: [
      { name_ar: "كفر الشيخ", name_en: "Kafr El Sheikh" },
      { name_ar: "دسوق", name_en: "Desouk" },
      { name_ar: "فوه", name_en: "Fuwwah" },
      { name_ar: "مطوبس", name_en: "Metoubes" },
      { name_ar: "بلطيم", name_en: "Baltim" },
      { name_ar: "الرياض", name_en: "Riyadh (Kafr El Sheikh)" }, // To distinguish
      { name_ar: "سيدي سالم", name_en: "Sidi Salem" },
      { name_ar: "قلين", name_en: "Qallin" },
      { name_ar: "بيلا", name_en: "Bella" },
      { name_ar: "الحامول", name_en: "Hamoul" },
      { name_ar: "البرلس", name_en: "Burullus" },
    ],
  },
  {
    id: "damietta",
    name_ar: "دمياط",
    name_en: "Damietta",
    cities: [
      { name_ar: "دمياط", name_en: "Damietta" },
      { name_ar: "دمياط الجديدة", name_en: "New Damietta" },
      { name_ar: "رأس البر", name_en: "Ras El Bar" },
      { name_ar: "فارسكور", name_en: "Faraskur" },
      { name_ar: "الزرقا", name_en: "Zarqa" },
      { name_ar: "كفر سعد", name_en: "Kafr Saad" },
      { name_ar: "كفر البطيخ", name_en: "Kafr El Battikh" },
      { name_ar: "عزبة البرج", name_en: "Ezbet El Borg" },
      { name_ar: "ميت أبو غالب", name_en: "Mit Abu Ghaleb" },
    ],
  },
  {
    id: "port_said",
    name_ar: "بورسعيد",
    name_en: "Port Said",
    cities: [
      { name_ar: "بورسعيد", name_en: "Port Said" }, // (أحياء: الشرق، العرب، الضواحي، المناخ، الزهور، الجنوب)
      { name_ar: "بورفؤاد", name_en: "Port Fuad" },
    ],
  },
  {
    id: "ismailia",
    name_ar: "الإسماعيلية",
    name_en: "Ismailia",
    cities: [
      { name_ar: "الإسماعيلية", name_en: "Ismailia" },
      { name_ar: "فايد", name_en: "Fayed" },
      { name_ar: "القنطرة غرب", name_en: "Qantara West" },
      { name_ar: "القنطرة شرق", name_en: "Qantara East" },
      { name_ar: "التل الكبير", name_en: "El Tal El Kebir" },
      { name_ar: "أبو صوير المحطة", name_en: "Abu Suweir El Mahatta" },
      { name_ar: "القصاصين الجديدة", name_en: "New Qassasin" },
    ],
  },
  {
    id: "suez",
    name_ar: "السويس",
    name_en: "Suez",
    cities: [
      { name_ar: "السويس", name_en: "Suez" }, // (أحياء: السويس، الأربعين، عتاقة، الجناين، فيصل)
    ],
  },
  {
    id: "beni_suef",
    name_ar: "بني سويف",
    name_en: "Beni Suef",
    cities: [
      { name_ar: "بني سويف", name_en: "Beni Suef" },
      { name_ar: "الواسطى", name_en: "El Wasta" },
      { name_ar: "ناصر", name_en: "Nasser" },
      { name_ar: "ببا", name_en: "Biba" },
      { name_ar: "إهناسيا", name_en: "Ihnasiya" },
      { name_ar: "سمسطا", name_en: "Sumusta El Waqf" },
      { name_ar: "الفشن", name_en: "El Fashn" },
      { name_ar: "بني سويف الجديدة", name_en: "New Beni Suef" },
    ],
  },
  {
    id: "faiyum",
    name_ar: "الفيوم",
    name_en: "Faiyum",
    cities: [
      { name_ar: "الفيوم", name_en: "Faiyum" },
      { name_ar: "سنورس", name_en: "Sinnuris" },
      { name_ar: "إطسا", name_en: "Itsa" },
      { name_ar: "طامية", name_en: "Tamiya" },
      { name_ar: "أبشواي", name_en: "Abshaway" },
      { name_ar: "يوسف الصديق", name_en: "Yusuf El Sediaq" },
      { name_ar: "الفيوم الجديدة", name_en: "New Faiyum" },
    ],
  },
  {
    id: "minya",
    name_ar: "المنيا",
    name_en: "Minya",
    cities: [
      { name_ar: "المنيا", name_en: "Minya" },
      { name_ar: "مغاغة", name_en: "Maghagha" },
      { name_ar: "بني مزار", name_en: "Beni Mazar" },
      { name_ar: "مطاي", name_en: "Matay" },
      { name_ar: "سمالوط", name_en: "Samalut" },
      { name_ar: "العدوة", name_en: "El Idwa" },
      { name_ar: "ملوي", name_en: "Mallawi" },
      { name_ar: "دير مواس", name_en: "Deir Mawas" },
      { name_ar: "أبو قرقاص", name_en: "Abu Qurqas" },
      { name_ar: "المنيا الجديدة", name_en: "New Minya" },
    ],
  },
  {
    id: "asyut",
    name_ar: "أسيوط",
    name_en: "Asyut",
    cities: [
      { name_ar: "أسيوط", name_en: "Asyut" },
      { name_ar: "ديروط", name_en: "Dairut" },
      { name_ar: "القوصية", name_en: "Al Qusiyyah" },
      { name_ar: "أبنوب", name_en: "Abnub" },
      { name_ar: "منفلوط", name_en: "Manfalut" },
      { name_ar: "الفتح", name_en: "El Fath" },
      { name_ar: "أبو تيج", name_en: "Abu Tig" },
      { name_ar: "الغنايم", name_en: "El Ghanayem" },
      { name_ar: "ساحل سليم", name_en: "Sahel Selim" },
      { name_ar: "البداري", name_en: "El Badari" },
      { name_ar: "صدفا", name_en: "Sidfa" },
      { name_ar: "أسيوط الجديدة", name_en: "New Asyut" },
    ],
  },
  {
    id: "sohag",
    name_ar: "سوهاج",
    name_en: "Sohag",
    cities: [
      { name_ar: "سوهاج", name_en: "Sohag" },
      { name_ar: "أخميم", name_en: "Akhmim" },
      { name_ar: "البلينا", name_en: "Al Balina" },
      { name_ar: "جرجا", name_en: "Girga" },
      { name_ar: "دار السلام", name_en: "Dar El Salam" },
      { name_ar: "جهينة", name_en: "Juhaynah" },
      { name_ar: "المراغة", name_en: "Maragha" },
      { name_ar: "المنشأة", name_en: "El Mansha" },
      { name_ar: "ساقلتة", name_en: "Saqultah" },
      { name_ar: "طما", name_en: "Tama" },
      { name_ar: "طهطا", name_en: "Tahta" },
      { name_ar: "سوهاج الجديدة", name_en: "New Sohag" },
      { name_ar: "الكوثر", name_en: "Kawthar" },
    ],
  },
  {
    id: "qena",
    name_ar: "قنا",
    name_en: "Qena",
    cities: [
      { name_ar: "قنا", name_en: "Qena" },
      { name_ar: "أبو تشت", name_en: "Abu Tesht" },
      { name_ar: "نجع حمادي", name_en: "Nag Hammadi" },
      { name_ar: "دشنا", name_en: "Deshna" },
      { name_ar: "الوقف", name_en: "El Waqf" },
      { name_ar: "قفط", name_en: "Qift" },
      { name_ar: "نقادة", name_en: "Naqada" },
      { name_ar: "قوص", name_en: "Qus" },
      { name_ar: "فرشوط", name_en: "Farshut" },
      { name_ar: "قنا الجديدة", name_en: "New Qena" },
    ],
  },
  {
    id: "luxor",
    name_ar: "الأقصر",
    name_en: "Luxor",
    cities: [
      { name_ar: "الأقصر", name_en: "Luxor" },
      { name_ar: "القرنة", name_en: "Qurna" },
      { name_ar: "أرمنت", name_en: "Armant" },
      { name_ar: "إسنا", name_en: "Esna" },
      { name_ar: "الطود", name_en: "Tod" },
      { name_ar: "البياضية", name_en: "Al Bayadiyah" },
      { name_ar: "الزينية", name_en: "Al Zayniyah" },
      { name_ar: "الأقصر الجديدة", name_en: "New Luxor" },
    ],
  },
  {
    id: "aswan",
    name_ar: "أسوان",
    name_en: "Aswan",
    cities: [
      { name_ar: "أسوان", name_en: "Aswan" },
      { name_ar: "دراو", name_en: "Daraw" },
      { name_ar: "كوم أمبو", name_en: "Kom Ombo" },
      { name_ar: "نصر النوبة", name_en: "Nasr El Nuba" },
      { name_ar: "كلابشة", name_en: "Kalabsha" },
      { name_ar: "إدفو", name_en: "Edfu" },
      { name_ar: "الرديسية", name_en: "Al Radisiyah" },
      { name_ar: "البصيلية", name_en: "Al Basiliyah" },
      { name_ar: "السباعية", name_en: "Al Sibaiyah" },
      { name_ar: "أبو سمبل", name_en: "Abu Simbel" },
      { name_ar: "أسوان الجديدة", name_en: "New Aswan" },
    ],
  },
  {
    id: "red_sea",
    name_ar: "البحر الأحمر",
    name_en: "Red Sea",
    cities: [
      { name_ar: "الغردقة", name_en: "Hurghada" },
      { name_ar: "رأس غارب", name_en: "Ras Gharib" },
      { name_ar: "سفاجا", name_en: "Safaga" },
      { name_ar: "القصير", name_en: "El Qoseir" },
      { name_ar: "مرسى علم", name_en: "Marsa Alam" },
      { name_ar: "الشلاتين", name_en: "Shalateen" },
      { name_ar: "حلايب", name_en: "Halaib" },
      { name_ar: "أبو رماد", name_en: "Abu Ramad" },
    ],
  },
  {
    id: "new_valley",
    name_ar: "الوادي الجديد",
    name_en: "New Valley (El Wadi El Gedid)",
    cities: [
      { name_ar: "الخارجة", name_en: "Kharga Oasis" },
      { name_ar: "الداخلة", name_en: "Dakhla Oasis" },
      { name_ar: "الفرافرة", name_en: "Farafra Oasis" },
      { name_ar: "باريس", name_en: "Baris Oasis" },
      { name_ar: "بلاط", name_en: "Balat" },
    ],
  },
  {
    id: "matruh",
    name_ar: "مطروح",
    name_en: "Matrouh",
    cities: [
      { name_ar: "مرسى مطروح", name_en: "Marsa Matruh" },
      { name_ar: "الحمام", name_en: "El Hamam" },
      { name_ar: "العلمين", name_en: "Alamein" },
      { name_ar: "الضبعة", name_en: "Dabaa" },
      { name_ar: "النجيلة", name_en: "Negela" },
      { name_ar: "براني", name_en: "Barrani" },
      { name_ar: "السلوم", name_en: "Sallum" },
      { name_ar: "سيوة", name_en: "Siwa Oasis" },
    ],
  },
  {
    id: "north_sinai",
    name_ar: "شمال سيناء",
    name_en: "North Sinai",
    cities: [
      { name_ar: "العريش", name_en: "Arish" },
      { name_ar: "الشيخ زويد", name_en: "Sheikh Zuweid" },
      { name_ar: "رفح", name_en: "Rafah" },
      { name_ar: "بئر العبد", name_en: "Bir al-Abed" },
      { name_ar: "الحسنة", name_en: "Hasana" },
      { name_ar: "نخل", name_en: "Nakhl" },
    ],
  },
  {
    id: "south_sinai",
    name_ar: "جنوب سيناء",
    name_en: "South Sinai",
    cities: [
      { name_ar: "الطور", name_en: "El Tor" },
      { name_ar: "شرم الشيخ", name_en: "Sharm El Sheikh" },
      { name_ar: "دهب", name_en: "Dahab" },
      { name_ar: "نويبع", name_en: "Nuweiba" },
      { name_ar: "طابا", name_en: "Taba" },
      { name_ar: "سانت كاترين", name_en: "Saint Catherine" },
      { name_ar: "أبو رديس", name_en: "Abu Redis" },
      { name_ar: "أبو زنيمة", name_en: "Abu Zenima" },
      { name_ar: "رأس سدر", name_en: "Ras Sedr" },
    ],
  },
];