// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ejvlxufsooygxjsrxofc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdmx4dWZzb295Z3hqc3J4b2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2Njk1ODAsImV4cCI6MjA2MzI0NTU4MH0.y-A-rDOt8eHlnotLbgZRBlkcDN3rwAFODKYKwso69gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Removed Database import as types file not exported
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);